// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBloYnerCdWm_lnMx2isrMW_rV7w6xE2Y',
    appId: '1:719266321350:web:b83cf53384a64be7c298c7',
    messagingSenderId: '719266321350',
    projectId: 'irrigationsystem-cfcab',
    authDomain: 'irrigationsystem-cfcab.firebaseapp.com',
    databaseURL: 'https://irrigationsystem-cfcab-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsystem-cfcab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkBiDQCNoA7ija-B8wgOGRTkdqA9TxyIQ',
    appId: '1:719266321350:android:68485f1cc1fc03ebc298c7',
    messagingSenderId: '719266321350',
    projectId: 'irrigationsystem-cfcab',
    databaseURL: 'https://irrigationsystem-cfcab-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsystem-cfcab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBloYnerCdWm_lnMx2isrMW_rV7w6xE2Y',
    appId: '1:719266321350:web:f40ddd970ae4baf2c298c7',
    messagingSenderId: '719266321350',
    projectId: 'irrigationsystem-cfcab',
    authDomain: 'irrigationsystem-cfcab.firebaseapp.com',
    databaseURL: 'https://irrigationsystem-cfcab-default-rtdb.firebaseio.com',
    storageBucket: 'irrigationsystem-cfcab.firebasestorage.app',
  );
}
